### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by philkunz** [vniehues/homebridge-linak#1]
Hey :)

Just panning through this. Are you trying to target Linak using Bluetooth (e.g. Ikea Idasen)?

Regards
Phil

**Comment by vniehues** [comment]
Hey @philkunz :) 

Yes this plugin allows you to control Linak desks like the Idasen. 
Because it is based on this [Idasen-Controller](https://github.com/rhyst/idasen-controller), it has the same limitations. 
I tried implementing all the bluetooth stuff myself but I gave up and resorted to just calling the implementations that are already there. 

The plugin _should_ work with any Linak controlled desk but I can't test it as I don't have the desks ;)

I'll add a readme soon for more information 

Cheers,
Vince

**Comment by vniehues** [comment]
I'm going to close this just to keep things tidy :) 
If you have any questions or input please feel free to open a new issue or contribute with a PR :)
